### ISSUE TITLE
Scheduling MySQL Backups with Laravel

### ISSUE THREAD

**Issue by iamgergo** [laravel/blog-contest-may-mayhem#13]
https://pineco.de/scheduling-mysql-backups-with-laravel/

**Comment by RicardoRamirezR** [comment]
@iamgergo If I may, I would suggest that you add a section to compress the resulting dumped file

**Comment by iamgergo** [comment]
@RicardoRamirezR Thank you for your suggestion! I thought to do that, but I tried to keep the post as small as I could. For sure, it would be useful! But I won't change anything to be fair in the competition. Thanks again!

**Comment by freekmurze** [comment]
Shamelessly plugging our backup page here.

It's easily installed into any Laravel app. It can dump your db and, together with files you can select in a config file, zip it and copy that zip to an external filesystem. It can also notify you when things go wrong.

https://docs.spatie.be/laravel-backup/v5/introduction

**Comment by iamgergo** [comment]
@freekmurze I started my post with saying if anyone needs a fully solution, should check your package. The post is not more but covering some possibilities.
