### ISSUE TITLE
Integrating Laravel with DataTables

### ISSUE THREAD

**Issue by bishoyAtif** [laravel/blog-contest-may-mayhem#39]
[https://medium.com/@BishoAtif/integrating-laravel-with-datatables-975b0bbf4009](https://medium.com/@BishoAtif/integrating-laravel-with-datatables-975b0bbf4009)

**Comment by kareemhamdy100** [comment]
good job

**Comment by Ahmed-Basher1** [comment]
Great work bisho 
keep going

**Comment by bishoyAtif** [comment]
@kareemhamdy100 @shams42 Thanks a lot, guys <3

**Comment by abslmbkr** [comment]
Keep going, My man. u r an Example.

**Comment by MahmoudElghzaly** [comment]
very good

**Comment by MoatazEldesoky** [comment]
good job

**Comment by Mostafa717** [comment]
Awesome

**Comment by Mahfouzer** [comment]
awesome work dude <3

**Comment by OmarAlsaqa** [comment]
Well Done

**Comment by elbakly** [comment]
@taylorotwell this guy seems to be lobbying votes, datatables seriously and they all seem from them same city
