### ISSUE TITLE
Upgrading a lower Version of Laravel to the latest Version (An instance of Laravel 5.2 to 5.6)

### ISSUE THREAD

**Issue by Shupscom** [laravel/blog-contest-may-mayhem#51]
https://medium.com/@olasupokazeem/upgrading-a-lower-version-of-laravel-to-the-latest-version-an-instance-of-laravel-5-2-to-5-6-602f9220420a

**Comment by shirshak55** [comment]
bro sorry to disappoint but there are too many problems.

1. This is not incomplete. 
2. Laravel docs upgrade guide is better.

Anyway you tried which is good :)
